apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: gateway
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
              {{- end }}
